### PR TITLE
Failing to create IPv6 socket is not always fatal.

### PR DESCRIPTION
**Pull request by F-i-f**
On IPv4-only hosts, socket(..., IPPROTO_IPV6, ...) will fail with EAFNOSUPPORT.
Keep going in this case.

### CODE REVIEW

**Comment by elc3leb** [comment]
On ppc64le  IPV4-only host , we still encounter the problem : 

```
[root@server tmp]# uname -r
4.18.0-305.19.1.el8_4.ppc64le
[root@server tmp]# ip a | grep inet6
[root@server tmp]# lsmod | grep ipv6
nf_defrag_ipv6         16306  1 nf_conntrack
[root@server tmp]# cat /proc/cmdline
root=/dev/mapper/rhel-root ro crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap ipv6.disable=1 console=hvc0,115200
```

```
[root@server tmp]# yppush -v passwd.byname
Cannot create UDP socket for AF_INET6: Address family not supported by protocol
Cannot create UDP socket for AF_INET6: Address family not supported by protocol
```

**Comment by thkukuk** [comment]
Beside that it is better to either enable IPv6 or remove the IPv6 addresses for your hostnames: are you sure your yppush version contains the patch?
Looks like you are using RHEL 8, and that ypserv package is far too old to have the patch.

**Comment by elc3leb** [comment]
We used  ypserv-4.0-6.20170331git5bfba76.el8.ppc64le

**Comment by elc3leb** [comment]
Hello, We finaly update ypserv rpm from Centos 8 AppStream , and it's OK. 
Thank for your reply.

**Pull request merged**
